server {
    listen 8446 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    add_header Strict-Transport-Security "max-age=63072000" always;
    server_tokens off;

    location /api/orders         { proxy_pass http://order-service:8080;   proxy_set_header X-Forwarded-Proto https; }
    location /api/internal/orders { proxy_pass http://order-service:8080;  proxy_set_header X-Forwarded-Proto https; }
    location /api/users          { proxy_pass http://user-service:8080;    proxy_set_header X-Forwarded-Proto https; }
    location /api/internal/users { proxy_pass http://user-service:8080;    proxy_set_header X-Forwarded-Proto https; }
    location /api/billing        { proxy_pass http://billing-service:8080; proxy_set_header X-Forwarded-Proto https; }
    location /api/internal/billing { proxy_pass http://billing-service:8080; proxy_set_header X-Forwarded-Proto https; }
    location /api/auth           { proxy_pass http://auth-service:8080;    proxy_set_header X-Forwarded-Proto https; }
    location /api/internal/auth  { proxy_pass http://auth-service:8080;    proxy_set_header X-Forwarded-Proto https; }
}
